# 프롬프트
# 당신은 구조화된 형식의 정보를 추출하여 지식 그래프를 구축하도록 설계된 최상위 알고리즘입니다.
# 다음 텍스트에서 엔티티(노드)를 추출하고 해당 유형을 지정하십시오. 
# 단, **반드시 아래에 제공된 NODES 목록에 있는 노드만 선택해야 합니다.** 
# 새로운 노드를 생성하거나 NODES 목록에 있는 노드와 정확히 일치하지 않는 이름을 사용하지 마십시오.

# 또한 이러한 노드들 간의 관계를 추출하십시오.
# 결과를 다음 형식의 JSON으로 반환하십시오.

# 추가 규칙:
# - NODES 목록에 있는 노드만 사용하십시오. 노드를 새로 만들거나 대체하지 마십시오.
# - 관계의 엔티티 중 하나라도 NODES 목록에 없으면 해당 관계는 건너뛰십시오.
# - 양쪽 끝점이 모두 NODES 목록에 있고 방향이 유형과 일치하는 유효한 관계만 출력하십시오.
# - `properties.outcome` 값은 반드시 제시된 키워드 중 문맥에 가장 적합한 하나를 선택하여 매핑합니다.

UPDATED_TEMPLATE = """
You are a top-tier algorithm designed for extracting information in structured formats to build a knowledge graph. 
Extract the entities (nodes) and specify their type from the following text, but **you MUST select nodes ONLY from the following predefined set** (see the provided NODES list below). 
Do not create any new nodes or use names that do not exactly match one in the NODES list.

Also extract the relationships between these nodes. 
Return the result as JSON using the following format:

{
  "nodes": [
    {"id": "N0", "label": "인간", "properties": {"name": "Ash Ketchum"}}
  ],
  "relationships": [
    {"type": "SOCIAL_INTERACTION", "start_node_id": "N0", "end_node_id": "N75", "properties": {"outcome": "Meeting, companionship, battle, confrontation, cooperation"}},
    {"type": "PARTNERSHIP", "start_node_id": "N0", "end_node_id": "N134", "properties": {"outcome": "Meeting, companionship, battle"}},
    {"type": "POKEMON_RELATION", "start_node_id": "N0", "end_node_id": "N134", "properties": {"outcome": "Meeting, companionship, battle, cooperation"}},
    {"type": "ANTAGONISM", "start_node_id": "N0", "end_node_id": "N144", "properties": {"outcome": "confrontation, battle"}},
    {"type": "INVOLVED_IN", "start_node_id": "N0", "end_node_id": "N144", "properties": {"outcome": "cooperation, battle"}},
    {"type": "TRAVELS_TO", "start_node_id": "N0", "end_node_id": "N157", "properties": {"outcome": "location"}},
    {"type": "EXPERIENCES", "start_node_id": "N0", "end_node_id": "N173", "properties": {"outcome": "evolution"}},
  ]
}

Additional rules:
- Use only nodes from the NODES list. Do not invent or substitute nodes.
- Skip any relationship if one of its entities is not in NODES.
- Only output valid relationships where both endpoints exist in NODES and the direction matches their types.
- The `properties.outcome` value must be mapped by selecting the one most appropriate for the context from the provided keywords.

NODES =
[
  {"id":"N0",  "label":"인간", "properties":{"name":"Ash Ketchum"}},
  {"id":"N1",  "label":"인간", "properties":{"name":"Misty"}},
  {"id":"N2",  "label":"인간", "properties":{"name":"Brock"}},
  {"id":"N3",  "label":"인간", "properties":{"name":"Tracey Sketchit"}},
  {"id":"N4",  "label":"인간", "properties":{"name":"Professor Oak"}},
  {"id":"N5",  "label":"인간", "properties":{"name":"Gary Oak"}},
  {"id":"N6",  "label":"인간", "properties":{"name":"Jessie"}},
  {"id":"N7",  "label":"인간", "properties":{"name":"James"}},
  {"id":"N8",  "label":"인간", "properties":{"name":"Professor Felina Ivy"}},
  {"id":"N9",  "label":"인간", "properties":{"name":"Professor Elm"}},
  {"id":"N10",  "label":"인간", "properties":{"name":"Professor Birch"}},
  {"id":"N11",  "label":"인간", "properties":{"name":"Casey"}},
  {"id":"N12",  "label":"인간", "properties":{"name":"May"}},
  {"id":"N13",  "label":"인간", "properties":{"name":"Max"}},
  {"id":"N14",  "label":"인간", "properties":{"name":"Norman"}},
  {"id":"N15",  "label":"인간", "properties":{"name":"Morrison"}},
  {"id":"N16",  "label":"인간", "properties":{"name":"Tyson"}},
  {"id":"N17",  "label":"인간", "properties":{"name":"Scott"}},
  {"id":"N18",  "label":"인간", "properties":{"name":"Brandon"}},
  {"id":"N19",  "label":"인간", "properties":{"name":"Paul"}},
  {"id":"N20",  "label":"인간", "properties":{"name":"Professor Rowan"}},
  {"id":"N21",  "label":"인간", "properties":{"name":"Hunter J"}},
  {"id":"N22",  "label":"인간", "properties":{"name":"Wallace"}},
  {"id":"N23",  "label":"인간", "properties":{"name":"Cyrus"}},
  {"id":"N24",  "label":"인간", "properties":{"name":"Looker"}},
  {"id":"N25",  "label":"인간", "properties":{"name":"Lyra"}},
  {"id":"N26",  "label":"인간", "properties":{"name":"Cynthia"}},
  {"id":"N27",  "label":"인간", "properties":{"name":"Tobias"}},
  {"id":"N28",  "label":"인간", "properties":{"name":"Iris"}},
  {"id":"N29",  "label":"인간", "properties":{"name":"Cilan"}},
  {"id":"N30",  "label":"인간", "properties":{"name":"Professor Juniper"}},
  {"id":"N31",  "label":"인간", "properties":{"name":"N"}},
  {"id":"N32",  "label":"인간", "properties":{"name":"Trip"}},
  {"id":"N33",  "label":"인간", "properties":{"name":"Bianca"}},
  {"id":"N34",  "label":"인간", "properties":{"name":"Stephan"}},
  {"id":"N35",  "label":"인간", "properties":{"name":"Georgia"}},
  {"id":"N36",  "label":"인간", "properties":{"name":"Burgundy"}},
  {"id":"N37",  "label":"인간", "properties":{"name":"Alder"}},
  {"id":"N38",  "label":"인간", "properties":{"name":"Colress"}},
  {"id":"N39",  "label":"인간", "properties":{"name":"Ghetsis"}},
  {"id":"N40",  "label":"인간", "properties":{"name":"Alexa"}},
  {"id":"N41",  "label":"인간", "properties":{"name":"Serena"}},
  {"id":"N42",  "label":"인간", "properties":{"name":"Clemont"}},
  {"id":"N43",  "label":"인간", "properties":{"name":"Bonnie"}},
  {"id":"N44",  "label":"인간", "properties":{"name":"Professor Sycamore"}},
  {"id":"N45",  "label":"인간", "properties":{"name":"Alain"}},
  {"id":"N46",  "label":"인간", "properties":{"name":"Lysandre"}},
  {"id":"N47",  "label":"인간", "properties":{"name":"Sawyer"}},
  {"id":"N48",  "label":"인간", "properties":{"name":"Malva"}},
  {"id":"N49",  "label":"인간", "properties":{"name":"Xerosic"}},
  {"id":"N50",  "label":"인간", "properties":{"name":"Mairin"}},
  {"id":"N51",  "label":"인간", "properties":{"name":"Lillie"}},
  {"id":"N52",  "label":"인간", "properties":{"name":"Kiawe"}},
  {"id":"N53",  "label":"인간", "properties":{"name":"Mallow"}},
  {"id":"N54",  "label":"인간", "properties":{"name":"Lana"}},
  {"id":"N55",  "label":"인간", "properties":{"name":"Sophocles"}},
  {"id":"N56",  "label":"인간", "properties":{"name":"Professor Kukui"}},
  {"id":"N57",  "label":"인간", "properties":{"name":"Samson Oak"}},
  {"id":"N58",  "label":"인간", "properties":{"name":"Gladion"}},
  {"id":"N59",  "label":"인간", "properties":{"name":"Lusamine"}},
  {"id":"N60",  "label":"인간", "properties":{"name":"Professor Burnet"}},
  {"id":"N61",  "label":"인간", "properties":{"name":"Faba"}},
  {"id":"N62",  "label":"인간", "properties":{"name":"Wicke"}},
  {"id":"N63",  "label":"인간", "properties":{"name":"Hau"}},
  {"id":"N64",  "label":"인간", "properties":{"name":"Guzma"}},
  {"id":"N65",  "label":"인간", "properties":{"name":"Goh"}},
  {"id":"N66",  "label":"인간", "properties":{"name":"Chloe Cerise"}},
  {"id":"N67",  "label":"인간", "properties":{"name":"Professor Cerise"}},
  {"id":"N68",  "label":"인간", "properties":{"name":"Leon"}},
  {"id":"N69",  "label":"인간", "properties":{"name":"Raihan"}},
  {"id":"N70",  "label":"인간", "properties":{"name":"Sonia"}},
  {"id":"N71",  "label":"인간", "properties":{"name":"Professor Magnolia"}},
  {"id":"N72",  "label":"인간", "properties":{"name":"Horace"}},
  {"id":"N73",  "label":"인간", "properties":{"name":"Steven Stone"}},
  {"id":"N74",  "label":"인간", "properties":{"name":"Lance"}},
  {"id":"N75",  "label":"인간", "properties":{"name":"Diantha"}},

  {"id":"N76",  "label":"포켓몬", "properties":{"name":"Pikachu"}},
  {"id":"N77",  "label":"포켓몬", "properties":{"name":"Meowth"}},
  {"id":"N78",  "label":"포켓몬", "properties":{"name":"Lapras"}},
  {"id":"N79",  "label":"포켓몬", "properties":{"name":"Snorlax"}},
  {"id":"N80",  "label":"포켓몬", "properties":{"name":"Togepi"}},
  {"id":"N81",  "label":"포켓몬", "properties":{"name":"Chikorita"}},
  {"id":"N82",  "label":"포켓몬", "properties":{"name":"Cyndaquil"}},
  {"id":"N83",  "label":"포켓몬", "properties":{"name":"Totodile"}},
  {"id":"N84",  "label":"포켓몬", "properties":{"name":"Bayleef"}},
  {"id":"N85",  "label":"포켓몬", "properties":{"name":"Noctowl"}},
  {"id":"N86",  "label":"포켓몬", "properties":{"name":"Larvitar"}},
  {"id":"N87",  "label":"포켓몬", "properties":{"name":"Torchic"}},
  {"id":"N88",  "label":"포켓몬", "properties":{"name":"Mudkip"}},
  {"id":"N89",  "label":"포켓몬", "properties":{"name":"Treecko"}},
  {"id":"N90",  "label":"포켓몬", "properties":{"name":"Groudon"}},
  {"id":"N91",  "label":"포켓몬", "properties":{"name":"Kyogre"}},
  {"id":"N92",  "label":"포켓몬", "properties":{"name":"Registeel"}},
  {"id":"N93",  "label":"포켓몬", "properties":{"name":"Regice"}},
  {"id":"N94",  "label":"포켓몬", "properties":{"name":"Regirock"}},
  {"id":"N95",  "label":"포켓몬", "properties":{"name":"Piplup"}},
  {"id":"N96",  "label":"포켓몬", "properties":{"name":"Turtwig"}},
  {"id":"N97",  "label":"포켓몬", "properties":{"name":"Chimchar"}},
  {"id":"N98",  "label":"포켓몬", "properties":{"name":"Gliscor"}},
  {"id":"N99",  "label":"포켓몬", "properties":{"name":"Regigigas"}},
  {"id":"N100",  "label":"포켓몬", "properties":{"name":"Darkrai"}},
  {"id":"N101",  "label":"포켓몬", "properties":{"name":"Latios"}},
  {"id":"N102",  "label":"포켓몬", "properties":{"name":"Snivy"}},
  {"id":"N103",  "label":"포켓몬", "properties":{"name":"Tepig"}},
  {"id":"N104",  "label":"포켓몬", "properties":{"name":"Oshawott"}},
  {"id":"N105",  "label":"포켓몬", "properties":{"name":"Meloetta"}},
  {"id":"N106",  "label":"포켓몬", "properties":{"name":"Reshiram"}},
  {"id":"N107",  "label":"포켓몬", "properties":{"name":"Greninja"}},
  {"id":"N108",  "label":"포켓몬", "properties":{"name":"Dedenne"}},
  {"id":"N109",  "label":"포켓몬", "properties":{"name":"Zygarde"}},
  {"id":"N110",  "label":"포켓몬", "properties":{"name":"Frogadier"}},
  {"id":"N111",  "label":"포켓몬", "properties":{"name":"Braixen"}},
  {"id":"N112",  "label":"포켓몬", "properties":{"name":"Luxray"}},
  {"id":"N113",  "label":"포켓몬", "properties":{"name":"Goodra"}},
  {"id":"N114",  "label":"포켓몬", "properties":{"name":"Noibat"}},
  {"id":"N115",  "label":"포켓몬", "properties":{"name":"Squishy"}},
  {"id":"N116",  "label":"포켓몬", "properties":{"name":"Rotom Dex"}},
  {"id":"N117",  "label":"포켓몬", "properties":{"name":"Nebby"}},
  {"id":"N118",  "label":"포켓몬", "properties":{"name":"Cosmog"}},
  {"id":"N119",  "label":"포켓몬", "properties":{"name":"Ultra Beasts"}},
  {"id":"N120",  "label":"포켓몬", "properties":{"name":"Solgaleo"}},
  {"id":"N121",  "label":"포켓몬", "properties":{"name":"Lunala"}},
  {"id":"N122",  "label":"포켓몬", "properties":{"name":"Poipole"}},
  {"id":"N123",  "label":"포켓몬", "properties":{"name":"Necrozma"}},
  {"id":"N124",  "label":"포켓몬", "properties":{"name":"Meltan"}},
  {"id":"N125",  "label":"포켓몬", "properties":{"name":"Melmetal"}},
  {"id":"N126",  "label":"포켓몬", "properties":{"name":"Shaymin"}},
  {"id":"N127",  "label":"포켓몬", "properties":{"name":"Nagadel"}},
  {"id":"N128",  "label":"포켓몬", "properties":{"name":"Raboot"}},
  {"id":"N129",  "label":"포켓몬", "properties":{"name":"Cinderace"}},
  {"id":"N130",  "label":"포켓몬", "properties":{"name":"Mew"}},
  {"id":"N131",  "label":"포켓몬", "properties":{"name":"Grookey"}},
  {"id":"N132",  "label":"포켓몬", "properties":{"name":"Suicune"}},
  {"id":"N133",  "label":"포켓몬", "properties":{"name":"Lucario"}},
  {"id":"N134",  "label":"포켓몬", "properties":{"name":"Eternatus"}},

  {"id":"N135",  "label":"조직", "properties":{"name":"Ultra Guardians"}},
  {"id":"N136",  "label":"조직", "properties":{"name":"Project Mew"}},

  {"id":"N137",  "label":"악당 단체", "properties":{"name":"Team Rocket"}},
  {"id":"N138",  "label":"악당 단체", "properties":{"name":"Team Magma"}},
  {"id":"N139",  "label":"악당 단체", "properties":{"name":"Team Aqua"}},
  {"id":"N140",  "label":"악당 단체", "properties":{"name":"Team Galactic"}},
  {"id":"N141",  "label":"악당 단체", "properties":{"name":"Team Plasma"}},
  {"id":"N142",  "label":"악당 단체", "properties":{"name":"Team Flare"}},
  {"id":"N143",  "label":"악당 단체", "properties":{"name":"Team Skull"}},
  {"id":"N144",  "label":"악당 단체", "properties":{"name":"Aether Foundation"}},

  {"id":"N145",  "label":"지역", "properties":{"name":"Kanto region"}},
  {"id":"N146",  "label":"지역", "properties":{"name":"Orange Archipelago"}},
  {"id":"N147",  "label":"지역", "properties":{"name":"Johto region"}},
  {"id":"N148",  "label":"지역", "properties":{"name":"Whirl Islands"}},
  {"id":"N149",  "label":"지역", "properties":{"name":"Hoenn region"}},
  {"id":"N150",  "label":"지역", "properties":{"name":"Sinnoh region"}},
  {"id":"N151",  "label":"지역", "properties":{"name":"Mt. Coronet"}},
  {"id":"N152",  "label":"지역", "properties":{"name":"Unova region"}},
  {"id":"N153",  "label":"지역", "properties":{"name":"Decolore Islands"}},
  {"id":"N154",  "label":"지역", "properties":{"name":"Kalos region"}},
  {"id":"N155",  "label":"지역", "properties":{"name":"Alola region"}},
  {"id":"N156",  "label":"지역", "properties":{"name":"Ultra Space"}},
  {"id":"N157",  "label":"지역", "properties":{"name":"Galar region"}},

  {"id":"N158",  "label":"대회", "properties":{"name":"Indigo Plateau Conference"}},
  {"id":"N159",  "label":"대회", "properties":{"name":"Orange League"}},
  {"id":"N160",  "label":"대회", "properties":{"name":"Silver Conference"}},
  {"id":"N161",  "label":"대회", "properties":{"name":"Battle Frontier"}},
  {"id":"N162",  "label":"대회", "properties":{"name":"Wallace Cup"}},
  {"id":"N163",  "label":"대회", "properties":{"name":"Lily of the Valley Conference"}},
  {"id":"N164",  "label":"대회", "properties":{"name":"Pokémon World Tournament Junior Cup"}},
  {"id":"N165",  "label":"대회", "properties":{"name":"Lumiose Conference"}},
  {"id":"N166",  "label":"대회", "properties":{"name":"Manalo Conference"}},
  {"id":"N167",  "label":"대회", "properties":{"name":"World Coronation Series"}},
  {"id":"N168",  "label":"대회", "properties":{"name":"Masters Eight Tournament"}},

  {"id":"N169",  "label":"현상", "properties":{"name":"Mega Evolution"}},
  {"id":"N170",  "label":"현상", "properties":{"name":"Bond Phenomenon"}},
  {"id":"N171",  "label":"현상", "properties":{"name":"Z-Moves"}},
  {"id":"N172",  "label":"현상", "properties":{"name":"Dynamax"}},
  {"id":"N173",  "label":"현상", "properties":{"name":"Gigantamax"}},
]
"""

# 영어 이름 → 한글 이름 변환 매핑 테이블
KOREAN_NODE_MAP = {
  "Ash Ketchum": "지우",
  "Misty": "이슬",
  "Brock": "웅",
  "Tracey Sketchit": "관철",
  "Professor Oak": "오박사",
  "Gary Oak": "오바람",
  "Jessie": "로사",
  "James": "로이",
  "Professor Felina Ivy": "미지박사",
  "Professor Elm": "공박사",
  "Professor Birch": "털보박사",
  "Casey": "나진",
  "May": "봄이",
  "Max": "정인",
  "Norman": "종길",
  "Morrison": "정권",
  "Tyson": "철희",
  "Scott": "기선",
  "Brandon": "기라",
  "Paul": "진철",
  "Professor Rowan": "마박사",
  "Hunter J": "포켓몬 사냥꾼 J",
  "Wallace": "윤진",
  "Cyrus": "태홍",
  "Looker": "핸섬",
  "Lyra": "금선",
  "Cynthia": "난천",
  "Tobias": "택열",
  "Iris": "아이리스",
  "Cilan": "덴트",
  "Professor Juniper": "주박사",
  "N": "N",
  "Trip": "슈티",
  "Bianca": "벨",
  "Stephan": "케니안",
  "Georgia": "카베르네",
  "Burgundy": "랭글레이",
  "Alder": "노고치",
  "Colress": "아크로마",
  "Ghetsis": "게치스",
  "Alexa": "팬지",
  "Serena": "세레나",
  "Clemont": "시트론",
  "Bonnie": "유리카",
  "Professor Sycamore": "플라타느박사",
  "Alain": "아란",
  "Lysandre": "플라드리",
  "Sawyer": "승태",
  "Malva": "파키라",
  "Xerosic": "크세로시키",
  "Mairin": "마농",
  "Lillie": "릴리에",
  "Kiawe": "키아웨",
  "Mallow": "마오",
  "Lana": "수련",
  "Sophocles": "마마네",
  "Professor Kukui": "쿠쿠이박사",
  "Samson Oak": "송호오",
  "Gladion": "글라디오",
  "Lusamine": "루자미네",
  "Professor Burnet": "버넷박사",
  "Faba": "자우보",
  "Wicke": "비케",
  "Hau": "하우",
  "Guzma": "구즈마",
  "Goh": "고우",
  "Chloe Cerise": "채하루",
  "Professor Cerise": "채박사",
  "Leon": "단데",
  "Raihan": "금랑",
  "Sonia": "소니아",
  "Professor Magnolia": "매그놀리아박사",
  "Horace": "진구",
  "Steven Stone": "성호",
  "Lance": "목호",
  "Diantha": "카르네",

  "Pikachu": "피카츄",
  "Meowth": "나옹",
  "Lapras": "라프라스",
  "Snorlax": "잠만보",
  "Togepi": "토게피",
  "Chikorita": "치코리타",
  "Cyndaquil": "브케인",
  "Totodile": "리아코",
  "Bayleef": "베이리프",
  "Noctowl": "야부엉",
  "Larvitar": "애버라스",
  "Torchic": "아차모",
  "Mudkip": "물짱이",
  "Treecko": "나무지기",
  "Groudon": "그란돈",
  "Kyogre": "가이오가",
  "Registeel": "레지스틸",
  "Regice": "레지아이스",
  "Regirock": "레지락",
  "Piplup": "팽도리",
  "Turtwig": "모부기",
  "Chimchar": "불꽃숭이",
  "Gliscor": "글라이온",
  "Regigigas": "레지기거스",
  "Darkrai": "다크라이",
  "Latios": "라티오스",
  "Snivy": "주리비얀",
  "Tepig": "뚜꾸리",
  "Oshawott": "수댕이",
  "Meloetta": "메로엣타",
  "Reshiram": "레시라무",
  "Greninja": "개굴닌자",
  "Dedenne": "데덴네",
  "Zygarde": "지이가르데",
  "Frogadier": "개굴반장",
  "Braixen": "테르나",
  "Luxray": "렌트라",
  "Goodra": "미끄래곤",
  "Noibat": "음뱃",
  "Squishy": "말랑이",
  "Rotom Dex": "로토무도감",
  "Nebby": "별구름",
  "Cosmog": "코스모그",
  "Ultra Beasts": "울트라비스트",
  "Solgaleo": "솔가레오",
  "Lunala": "루날라",
  "Poipole": "베베놈",
  "Necrozma": "네크로즈마",
  "Meltan": "멜탄",
  "Melmetal": "멜메탈",
  "Shaymin": "쉐이미",
  "Nagadel": "아고용",
  "Raboot": "래비풋",
  "Cinderace": "에이스번",
  "Mew": "뮤",
  "Grookey": "흥나숭",
  "Suicune": "스이쿤",
  "Lucario": "루카리오",
  "Eternatus": "무한다이노",

  "Ultra Guardians": "울트라가디언즈",
  "Project Mew": "프로젝트 뮤",

  "Team Rocket": "로켓단",
  "Team Magma": "마그마단",
  "Team Aqua": "아쿠아단",
  "Team Galactic": "갤럭시단",
  "Team Plasma": "플라즈마단",
  "Team Flare": "플레어단",
  "Team Skull": "스컬단",
  "Aether Foundation": "에테르재단",

  "Kanto region": "관동지방",
  "Orange Archipelago": "오렌지제도",
  "Johto region": "성도지방",
  "Whirl Islands": "소용돌이열도",
  "Hoenn region": "호연지방",
  "Sinnoh region": "신오지방",
  "Mt. Coronet": "천관산",
  "Unova region": "하나지방",
  "Decolore Islands": "데코로라제도",
  "Kalos region": "칼로스지방",
  "Alola region": "알로라지방",
  "Ultra Space": "울트라스페이스",
  "Galar region": "가라르지방",

  "Indigo Plateau Conference": "석영대회",
  "Orange League": "오렌지리그",
  "Silver Conference": "은빛대회",
  "Battle Frontier": "배틀프런티어",
  "Wallace Cup": "윤진컵",
  "Lily of the Valley Conference": "신오리그 영란대회",
  "Pokémon World Tournament Junior Cup": "포켓몬 월드 토너먼트 주니어컵",
  "Lumiose Conference": "칼로스리그 미르대회",
  "Manalo Conference": "알로라리그 마날로대회",
  "World Coronation Series": "포켓몬 월드 챔피언십",
  "Masters Eight Tournament": "마스터즈 에이트 토너먼트",

  "Mega Evolution": "메가진화",
  "Bond Phenomenon": "유대현상",
  "Z-Moves": "Z기술",
  "Dynamax": "다이맥스",
  "Gigantamax": "거다이맥스"
}