FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    openjdk-21-jdk \
    wget \
    curl \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

# Java 환경 변수
ENV JAVA_HOME=/usr/lib/jvm/java-21-openjdk-amd64
ENV PATH=$JAVA_HOME/bin:$PATH

# Spark 환경 변수
ENV PYSPARK_PYTHON=python3
ENV PYSPARK_DRIVER_PYTHON=python3
ENV SPARK_HOME=/opt/spark

# uv 설치
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN pip install uv

WORKDIR /workspace

# 의존성 캐싱
COPY app/pyproject.toml app/uv.lock ./
RUN uv sync --frozen --no-dev

# 앱 코드 복사
COPY app /workspace/app

WORKDIR /workspace/app

CMD ["uv", "run", "fastapi", "run", "--host", "0.0.0.0", "--port", "8000"]