services:
  mariadb:
    container_name: mariadb
    image: mariadb:12.1.2
    restart: always
    ports:
      - 3306:3306
    networks:
      - spark-network
    volumes:
      - ./conf.d:/etc/mysql/conf.d:ro
      - data-mariadb:/var/lib/mysql:rw
    environment:
      - MARIADB_HOST=localhost
      - MARIADB_PORT=3306
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=edu
      - TZ=Asia/Seoul
      - LC_ALL:en_US.UTF-8

  spark-master:
    # image: apache/spark:4.1.1-java21-python3
    image: my-spark:latest
    container_name: spark-master
    user: root
    environment:
      # - SPARK_MODE=master
      # - SPARK_MASTER_PORT=7077
      # - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ./data:/opt/spark/data:rw
    ports:
      - "8080:8080"
      - "7077:7077"
      - "10001:10001"
    networks:
      - spark-network
    # command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    command: start-master.sh

  spark-worker-1:
    # image: apache/spark:4.1.1-java21-python3
    image: my-spark:latest
    container_name: spark-worker-1
    user: root
    environment:
      #- SPARK_MODE=worker
      #- SPARK_MASTER_URL=spark://spark-master:7077
      # - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8081:8081"
      - "10002:10002"
      - "11002:11002"
    volumes:
      - spark-work-1:/opt/spark/work
      - ./data:/opt/spark/data:rw
    depends_on:
      - spark-master
    networks:
      - spark-network
    # command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    command: start-worker.sh spark://spark-master:7077

  spark-worker-2:
    # image: apache/spark:4.1.1-java21-python3
    image: my-spark:latest
    container_name: spark-worker-2
    user: root
    environment:
      # - SPARK_MODE=worker
      # - SPARK_MASTER_URL=spark://spark-master:7077
      # - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
    ports:
      - "8082:8081"
      - "10003:10002"
      - "11003:11002"
    volumes:
      - spark-work-2:/opt/spark/work
      - ./data:/opt/spark/data:rw
    depends_on:
      - spark-master
    networks:
      - spark-network
    # command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    command: start-worker.sh spark://spark-master:7077

networks:
  spark-network:
    driver: bridge

volumes:
  spark-work-1:
  spark-work-2:
  data-mariadb:
    external: true # 기존 Volume 사용 옵션
